using Tyuiu.AfoninME.Sprint3.Task2.V27.Lib;
DataService ds = new DataService();
Console.Title = "Спринт #3| Выполнил: Афонин М.Е. | ИСТНб-25-1";
Console.WriteLine("****************************************************");
Console.WriteLine("* Спринт #3                                        *");
Console.WriteLine("* Тема:Оператор цикла while                        *");
Console.WriteLine("* Задание #2                                       *");
Console.WriteLine("* Вариант #27                                      *");
Console.WriteLine("* Выполнил: Афонин Максим Евгеньевич | ИСТНб-25-1  *");
Console.WriteLine("****************************************************");
Console.WriteLine("* УСЛОВИЕ:                                         *");
Console.WriteLine("* Написать программу используя цикл do...while,    *");
Console.WriteLine("* которая вычисляет сумму ряда по формуле,при x = 5*");

Console.WriteLine("****************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                 *");
Console.WriteLine("****************************************************");
int value = 5;
int startValue = 1;
int stopValue = 14;
Console.WriteLine("Переменная X=" + value);
Console.WriteLine("Старт шага =" + startValue);
Console.WriteLine("Конец шага =" + stopValue);
Console.WriteLine("****************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                       *");
Console.WriteLine("*****************************************************");
Console.WriteLine(" Сумма ряда =" + ds.GetSumSeries(value, startValue, stopValue));
Console.ReadKey();
